variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - test
  - build
  - deploy

cache:
  key: python-onig-cache
  paths:
    - .cache/
    - deps

checks:
  stage: build
  image: python:latest
  script:
    - pip install poetry
    - poetry install


.manylinux-build-wheels:
  image: quay.io/pypa/manylinux1_x86_64
  stage: build
  script:
    - ./helpers/ci-build-manylinux-wheels.sh
  artifacts:
    paths:
      - wheels

manylinux1-cp38-x86_64:
    extends:
        - .manylinux-build-wheels
    variables:
        PLATFORM: manylinux1_x86_64
        PYTHON_HOME: /opt/python/cp38-cp38/


deploy-wheels:
  stage: deploy
  image: python:latest
  only:
    - tags
  dependencies:
    - manylinux1-cp38-x86_64
  script:
    - pip install twine
    - twine upload -u $PYPI_USER -p $PYPI_PASS --skip-existing wheels/*.whl
