environment:
  global:
    PYPI_USER: koehlma
    PYPI_PASS:
      secure: fNXSRnU45IOyN9G3z7RuslLSEXjW4qSHZdV7o1F7/Nc=
  matrix:
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
  - "python --version"
  - "python -m ensurepip"
  - "pip install poetry"
  - "poetry install"

build_script:
  - "SET APPVEYOR=True"
  - "poetry build"

deploy_script:
  - ps: ./helpers/appveyor-deploy-pypi.ps1

deploy: on

artifacts:
  - path: dist\*
