environment:
  global:
    PYPI_USER: koehlma
    PYPI_PASS:
      secure: +P3od+i9tlN8YdMfoZGOQBFQ1ogjUGFmNEQNa9KfO60=
  matrix:
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"


install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Environment variables:"
  - ps: "Get-ChildItem Env:"

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
  - "python --version"
  - "python -m ensurepip"
  - "pip install poetry"
  - "poetry install"

build_script:
  - "SET APPVEYOR=True"
  - "poetry build"

deploy_script:
  - ps: ./helpers/appveyor-deploy-pypi.ps1

deploy: on

artifacts:
  - path: dist\*
